In [1]:
%pylab inline
import numpy as np


Populating the interactive namespace from numpy and matplotlib


In [21]:
n_attributes = 10
attributes = np.arange(n_attributes)

n_options = 5
options = [attributes[np.random.binomial(1, p_inclusion, size=n_attributes)==1] for _ in range(n_options)]

In [22]:
options

[array([1, 2, 5, 6, 8]),
 array([], dtype=int64),
 array([1, 4, 6, 8, 9]),
 array([0, 6, 9]),
 array([0, 7])]

In [ ]:
choices = options.copy()
while choices > 1:
    
    